// src/events/event.constants.ts
export const EVENTS = {
  DISRUPTION_DETECTED: "DISRUPTION_DETECTED",

  CLAIM_CREATED: "CLAIM_CREATED",

  FRAUD_SCORE_COMPUTED: "FRAUD_SCORE_COMPUTED",

  CLAIM_APPROVED: "CLAIM_APPROVED",
  CLAIM_REJECTED: "CLAIM_REJECTED",

  PAYMENT_PROCESSED: "PAYMENT_PROCESSED",
  PAYMENT_FAILED: "PAYMENT_FAILED",
} as const

export type EventType = typeof EVENTS[keyof typeof EVENTS]